# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TumblrPt1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TumblrPt1
  pod 'AlamofireImage'

  target 'TumblrPt1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TumblrPt1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
