# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flixpart1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flixpart1
  pod "AlamofireImage"

  target 'Flixpart1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flixpart1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
